#!/usr/bin/perl
# list of running binaries, skip what's not recognized

opendir(D, "/proc") or die $!;
for (readdir(D)) {
	next unless /\d+/;
	my $cmdfull=`cat "/proc/$_/cmdline" 2>/dev/null`;
	my $cmd=(split("\000", $cmdfull))[0];
	chomp $cmd;
	next if $cmd eq '';
	print $cmd, "\n";
}
closedir(D);
